### ISSUE TITLE
Problem with readme

### ISSUE THREAD

**Issue by agatiwi** [marcol13/si_choose_your_typeface#1]
As an international user I had to translate your readme to english using Google translator

I feel offended, that there is absolutly no usefull info

I would like to wish you a great day, but this project doesnt deserve this

**Comment by marcol13** [comment]
Hello @agatiwi,

thank you for your comment. I am sorry that you must faced with non-english README. Unfortunately this project was prepared for Polish classes so this file have to be written in adequate language (so in Polish). If you want complain I can send you an email to my academic teacher so you can correspond with him.

Greetings from onion lands,
Marcin Krueger
